#!/usr/bin/env sh

#  A development tool

CONTAINER="${1^^}"

if [ "$CONTAINER" == "" ] || [ "$CONTAINER" == "-H" ] || [ "$CONTAINER" == "--HELP" ]; then
    echo "Rebuild and restart a container defined in a docker-compose.yaml file:" 
    echo "   rebuild scraper"
    echo "   rebuild www"
    exit
fi

sudo podman compose down "$1"
sudo podman compose rm "$1"
SUBDIR=$(basename "$(pwd)")
sudo podman rmi "${SUBDIR}-$1"
sudo podman compose up --detach "$1"
