#!/usr/bin/env sh

CONTAINER="${1^^}"

if [ "$CONTAINER" == "" ] || [ "$CONTAINER" == "-H" ] || [ "$CONTAINER" == "--HELP" ]; then
    echo "Rebuild and restart a container defined in a docker-compose.yaml file:" 
    echo "   rebuild scraper"
    echo "   rebuild www"
    exit
fi

podman compose down "$1"
podman compose rm "$1"
SUBDIR=$(basename "$(pwd)")
podman rmi "${SUBDIR}-$1"
podman compose up --detach "$1"
