#  Combines some of the default ssl.conf plus the recommended config from
#  https://mozilla.github.io/server-side-tls/ssl-config-generator/

Listen 443 https

SSLPassPhraseDialog exec:/usr/libexec/httpd-ssl-pass-dialog

SSLSessionCache         shmcb:/run/httpd/sslcache(512000)
SSLSessionCacheTimeout  300

SSLRandomSeed startup file:/dev/urandom  256
SSLRandomSeed connect builtin

SSLCryptoDevice builtin

#  Mozilla Configuration "modern" settings, for servers "with clients that
#  support TLS 1.3 and don't need backward compatibility"
#  Nagios and wget don't work if TLSv1.2 is disabled
##SSLProtocol            all -SSLv3 -TLSv1 -TLSv1.1 -TLSv1.2

#  Mozilla Configuration "intermediate" settings, for "general-purpose servers
#  with a variety of clients, recommended for almost all systems"
#SSLProtocol            all -SSLv3 -TLSv1 -TLSv1.1
SSLCipherSuite          ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384

SSLHonorCipherOrder     off
SSLSessionTickets       off

SSLUseStapling          On
SSLStaplingCache        "shmcb:logs/ssl_stapling(32768)"
