################################################################################
#  dhtsearch.daveking.com
################################################################################

#  Write messages to the console via stderr for Docker container logs during development.
#  Disable in production so that fail2ban can be used against the the logs.
#ErrorLog "/dev/stderr"
#<IfModule log_config_module>
#    CustomLog "/dev/stderr" combined
#</IfModule>

<VirtualHost *:80>
    ServerName dhtsearch.daveking.com
    RewriteEngine On
    RewriteRule ^(.*)$ https://%{HTTP_HOST}$1 [R=301,L]
</VirtualHost>

<VirtualHost *:443>
    ServerName dhtsearch.daveking.com

    SSLEngine on
    SSLCertificateFile /etc/letsencrypt/fullchain.pem
    SSLCertificateKeyFile /etc/letsencrypt/privkey.pem

    Protocols h2 http/1.1

    Header always set Strict-Transport-Security "max-age=63072000; includeSubdomains"

    RewriteEngine On
    
    # if the request matches a directory or file name, use those directly,
    # otherwise forward the request to index.php as a function call
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-f
    RewriteCond %{DOCUMENT_ROOT}%{REQUEST_FILENAME} !-d
    RewriteRule (.*) /index.php$1

    #  Probably redundant
    DocumentRoot "/var/www/html"
    <Directory "/var/www/html">
        AllowOverride None
        Options -Indexes
        Require all granted
    </Directory>

</VirtualHost>
